name: 'Automatic up-merge action'
description: 'Creates a pull request to merge changes up to the next branch based on a pattern'
author: 'alcaeus'

branding:
  icon: 'heart'
  color: 'red'

inputs:
  ref:
    description: 'The ref being pushed'
    required: true
  branchNamePattern:
    description: 'Pattern to use for branch names. Use <major> and <minor> for version placeholders'
    required: false
    default: '<major>.<minor>'
  fallbackBranch:
    description: 'A branch to fall back on if no next branch matching the pattern was found'
    required: false
  enableAutoMerge:
    description: 'If non-empty, enables auto-merge on the pull request'
    required: false
    default: 'false'

outputs:
  branchName:
    description: 'The name of the generated branch'
  pullRequestUrl:
    description: 'URL of the generated pull request'

runs:
  using: node20
  main: dist/create-pr/index.js
