name: 'Get next merge-up branch'
description: 'Detects what branch the given branch can be merged up to'
author: 'alcaeus'

inputs:
  ref:
    description: 'The ref to merge up'
    required: true
  branchNamePattern:
    description:
      'Pattern to use for branch names. Use <major> and <minor> for version
      placeholders'
    required: false
    default: '<major>.<minor>'
  devBranchNamePattern:
    description:
      'Pattern to use for dev branch names. Use <major> for version placeholders'
    required: false
    default: ''
  fallbackBranch:
    description:
      'A branch to fall back on if no next branch matching the pattern was found'
    required: false
  ignoredBranches:
    description: 'JSON list of branches to ignore'
    required: false
    default: '[]'

outputs:
  hasNextBranch:
    description: 'Whether there is a branch to merge up to'
  branchName:
    description: 'The name of the branch to merge up to'

runs:
  using: node20
  main: ../dist/get-next-branch/index.js
